/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.webhooks.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Webhook service. Represents a row in the &quot;Webhooks_Webhook&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.webhooks.model.impl.WebhookModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.webhooks.model.impl.WebhookImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Webhook
 * @generated
 */
@ProviderType
public interface WebhookModel
	extends BaseModel<Webhook>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a webhook model instance should use the {@link Webhook} interface instead.
	 */

	/**
	 * Returns the primary key of this webhook.
	 *
	 * @return the primary key of this webhook
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this webhook.
	 *
	 * @param primaryKey the primary key of this webhook
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this webhook.
	 *
	 * @return the uuid of this webhook
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this webhook.
	 *
	 * @param uuid the uuid of this webhook
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the webhook ID of this webhook.
	 *
	 * @return the webhook ID of this webhook
	 */
	public long getWebhookId();

	/**
	 * Sets the webhook ID of this webhook.
	 *
	 * @param webhookId the webhook ID of this webhook
	 */
	public void setWebhookId(long webhookId);

	/**
	 * Returns the group ID of this webhook.
	 *
	 * @return the group ID of this webhook
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this webhook.
	 *
	 * @param groupId the group ID of this webhook
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this webhook.
	 *
	 * @return the company ID of this webhook
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this webhook.
	 *
	 * @param companyId the company ID of this webhook
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this webhook.
	 *
	 * @return the user ID of this webhook
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this webhook.
	 *
	 * @param userId the user ID of this webhook
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this webhook.
	 *
	 * @return the user uuid of this webhook
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this webhook.
	 *
	 * @param userUuid the user uuid of this webhook
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this webhook.
	 *
	 * @return the user name of this webhook
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this webhook.
	 *
	 * @param userName the user name of this webhook
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this webhook.
	 *
	 * @return the create date of this webhook
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this webhook.
	 *
	 * @param createDate the create date of this webhook
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this webhook.
	 *
	 * @return the modified date of this webhook
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this webhook.
	 *
	 * @param modifiedDate the modified date of this webhook
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the webhook url of this webhook.
	 *
	 * @return the webhook url of this webhook
	 */
	@AutoEscape
	public String getWebhookURL();

	/**
	 * Sets the webhook url of this webhook.
	 *
	 * @param webhookURL the webhook url of this webhook
	 */
	public void setWebhookURL(String webhookURL);

	/**
	 * Returns the api key of this webhook.
	 *
	 * @return the api key of this webhook
	 */
	@AutoEscape
	public String getApiKey();

	/**
	 * Sets the api key of this webhook.
	 *
	 * @param apiKey the api key of this webhook
	 */
	public void setApiKey(String apiKey);

	@Override
	public Webhook cloneWithOriginalValues();

}