components:
    schemas:
        Webhook:
            properties:
                url:
                    description: The URL of the Webhook
                    type: string
                apiKey:
                    description: The apiKey for the authentication
                    type: string
        WebhookEntity:
            description:
                Represents the entity which events will send to the Webhook specified
            properties:
                entity:
                    type: string
                webhookId:
                    format: int64
                    type: integer
info:
    description:
        "WebhooksRest REST API. A Java client JAR is available for use with the group ID 'com.liferay', artifact ID
        'com.liferay.headless.webhooks.client', and version '1.0.0'."
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "WebhooksRest"
    version: v1.0
openapi: 3.0.1
paths:
    "/sites/{siteId}/webhooks":
        get:
            description:
                Retrieves a Site's webhooks.
            operationId: getSiteWebhooksPage
            parameters:
                - in: path
                  name: siteId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Webhook"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Webhook"
                                type: array
            tags: ["Webhook"]
        post:
            description:
                Creates a new Webhook in a Site.
            operationId: postSiteWebhook
            parameters:
                - in: path
                  name: siteId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Webhook"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Webhook"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Webhook"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Webhook"
            tags: [ "Webhook" ]
    "/webhooks/{webhookId}":
        delete:
            description:
                Deletes the webhook and return a 204 if the operation succeeds.
            operationId: deleteWebhook
            parameters:
                - in: path
                  name: webhookId
                  required: true
                  schema:
                      type: string
            responses:
                204:
                    content:
                        application/json: { }
                        application/xml: { }
            tags: [ "Webhook" ]
        get:
            description:
                Retrieves a Webhook.
            operationId: getWebhook
            parameters:
                - in: path
                  name: webhookId
                  required: true
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Webhook"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Webhook"
            tags: [ "Webhook" ]
    "/sites/{siteId}/webhooksEntities":
        get:
            description:
                Retrieves all the webhooks entities of a Site
            parameters:
                - in: path
                  name: siteId
                  required: true
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json:
                          schema:
                              items:
                                  $ref: "#/components/schemas/WebhookEntity"
                              type: array
            tags: ["WebhookEntity"]
        post:
            description:
                Creates a new webhook entity in a Site
            parameters:
                - in: path
                  name: siteId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/WebhookEntity"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/WebhookEntity"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/WebhookEntity"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/WebhookEntity"
            tags: [ "WebhookEntity" ]
    "/webhook-entity/{webhookEntityId}":
        delete:
            description:
                Deletes the webhook entity and return a 204 if the operation succeeds.
            parameters:
                - in: path
                  name: webhookEntityId
                  required: true
                  schema:
                      type: string
            responses:
                204:
                    content:
                        application/json: { }
                        application/xml: { }
            tags: [ "WebhookEntity" ]
        get:
            description:
                Retrieves a Webhook Entity.
            parameters:
                - in: path
                  name: webhookEntityId
                  required: true
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/WebhookEntity"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/WebhookEntity"
            tags: [ "WebhookEntity" ]