components:
    schemas:
        !#objectDefinitionName#!:
            properties:
                date:
                    description:
                        The object date.
                    format: date-time
                    readOnly: true
                    type: string
                    x-field-definition:
                        name: createDate
                objectField:
                    description:
                        The object custom field.
                    type: string
                    x-field-definition:
                        name: !#objectFieldName#!
            x-schema-definition:
                entityName: "com.liferay.object.model.ObjectDefinition#!#objectDefinitionId#!"
info:
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: ""
    version: v1.0
openapi: "3.0.1"
paths:
    "/!#objectDefinitionPluralName#!/{id}":
        get:
            operationId: getTestEntry
            parameters:
                - in: path
                  name: id
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/!#objectDefinitionName#!"
            tags: ["!#objectDefinitionName#!"]
            x-operation-definition:
                type: "getByPrimaryKey"