/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.webhooks.model.impl;

import com.liferay.webhooks.model.Webhook;
import com.liferay.webhooks.service.WebhookLocalServiceUtil;

/**
 * The extended model base implementation for the Webhook service. Represents a row in the &quot;Webhooks_Webhook&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link WebhookImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see WebhookImpl
 * @see Webhook
 * @generated
 */
public abstract class WebhookBaseImpl
	extends WebhookModelImpl implements Webhook {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a webhook model instance should use the <code>Webhook</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			WebhookLocalServiceUtil.addWebhook(this);
		}
		else {
			WebhookLocalServiceUtil.updateWebhook(this);
		}
	}

}