/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.webhooks.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.webhooks.model.Webhook;
import com.liferay.webhooks.model.WebhookModel;
import com.liferay.webhooks.model.WebhookSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Webhook service. Represents a row in the &quot;Webhooks_Webhook&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>WebhookModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link WebhookImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see WebhookImpl
 * @generated
 */
@JSON(strict = true)
public class WebhookModelImpl
	extends BaseModelImpl<Webhook> implements WebhookModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a webhook model instance should use the <code>Webhook</code> interface instead.
	 */
	public static final String TABLE_NAME = "Webhooks_Webhook";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"webhookId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"webhookURL", Types.VARCHAR}, {"apiKey", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("webhookId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("webhookURL", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("apiKey", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Webhooks_Webhook (uuid_ VARCHAR(75) null,webhookId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,webhookURL VARCHAR(75) null,apiKey VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table Webhooks_Webhook";

	public static final String ORDER_BY_JPQL =
		" ORDER BY webhook.createDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Webhooks_Webhook.createDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long WEBHOOKURL_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CREATEDATE_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static Webhook toModel(WebhookSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Webhook model = new WebhookImpl();

		model.setUuid(soapModel.getUuid());
		model.setWebhookId(soapModel.getWebhookId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setWebhookURL(soapModel.getWebhookURL());
		model.setApiKey(soapModel.getApiKey());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<Webhook> toModels(WebhookSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Webhook> models = new ArrayList<Webhook>(soapModels.length);

		for (WebhookSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public WebhookModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _webhookId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setWebhookId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _webhookId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Webhook.class;
	}

	@Override
	public String getModelClassName() {
		return Webhook.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Webhook, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Webhook, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Webhook, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Webhook)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Webhook, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Webhook, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Webhook)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Webhook, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Webhook, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Webhook>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Webhook.class.getClassLoader(), Webhook.class, ModelWrapper.class);

		try {
			Constructor<Webhook> constructor =
				(Constructor<Webhook>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Webhook, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Webhook, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Webhook, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Webhook, Object>>();
		Map<String, BiConsumer<Webhook, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Webhook, ?>>();

		attributeGetterFunctions.put("uuid", Webhook::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Webhook, String>)Webhook::setUuid);
		attributeGetterFunctions.put("webhookId", Webhook::getWebhookId);
		attributeSetterBiConsumers.put(
			"webhookId", (BiConsumer<Webhook, Long>)Webhook::setWebhookId);
		attributeGetterFunctions.put("groupId", Webhook::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Webhook, Long>)Webhook::setGroupId);
		attributeGetterFunctions.put("companyId", Webhook::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Webhook, Long>)Webhook::setCompanyId);
		attributeGetterFunctions.put("userId", Webhook::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Webhook, Long>)Webhook::setUserId);
		attributeGetterFunctions.put("userName", Webhook::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Webhook, String>)Webhook::setUserName);
		attributeGetterFunctions.put("createDate", Webhook::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Webhook, Date>)Webhook::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Webhook::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<Webhook, Date>)Webhook::setModifiedDate);
		attributeGetterFunctions.put("webhookURL", Webhook::getWebhookURL);
		attributeSetterBiConsumers.put(
			"webhookURL", (BiConsumer<Webhook, String>)Webhook::setWebhookURL);
		attributeGetterFunctions.put("apiKey", Webhook::getApiKey);
		attributeSetterBiConsumers.put(
			"apiKey", (BiConsumer<Webhook, String>)Webhook::setApiKey);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getWebhookId() {
		return _webhookId;
	}

	@Override
	public void setWebhookId(long webhookId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_webhookId = webhookId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getWebhookURL() {
		if (_webhookURL == null) {
			return "";
		}
		else {
			return _webhookURL;
		}
	}

	@Override
	public void setWebhookURL(String webhookURL) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_webhookURL = webhookURL;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalWebhookURL() {
		return getColumnOriginalValue("webhookURL");
	}

	@JSON
	@Override
	public String getApiKey() {
		if (_apiKey == null) {
			return "";
		}
		else {
			return _apiKey;
		}
	}

	@Override
	public void setApiKey(String apiKey) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_apiKey = apiKey;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Webhook.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Webhook.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Webhook toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Webhook>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		WebhookImpl webhookImpl = new WebhookImpl();

		webhookImpl.setUuid(getUuid());
		webhookImpl.setWebhookId(getWebhookId());
		webhookImpl.setGroupId(getGroupId());
		webhookImpl.setCompanyId(getCompanyId());
		webhookImpl.setUserId(getUserId());
		webhookImpl.setUserName(getUserName());
		webhookImpl.setCreateDate(getCreateDate());
		webhookImpl.setModifiedDate(getModifiedDate());
		webhookImpl.setWebhookURL(getWebhookURL());
		webhookImpl.setApiKey(getApiKey());

		webhookImpl.resetOriginalValues();

		return webhookImpl;
	}

	@Override
	public Webhook cloneWithOriginalValues() {
		WebhookImpl webhookImpl = new WebhookImpl();

		webhookImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		webhookImpl.setWebhookId(
			this.<Long>getColumnOriginalValue("webhookId"));
		webhookImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		webhookImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		webhookImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		webhookImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		webhookImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		webhookImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		webhookImpl.setWebhookURL(
			this.<String>getColumnOriginalValue("webhookURL"));
		webhookImpl.setApiKey(this.<String>getColumnOriginalValue("apiKey"));

		return webhookImpl;
	}

	@Override
	public int compareTo(Webhook webhook) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(), webhook.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Webhook)) {
			return false;
		}

		Webhook webhook = (Webhook)object;

		long primaryKey = webhook.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Webhook> toCacheModel() {
		WebhookCacheModel webhookCacheModel = new WebhookCacheModel();

		webhookCacheModel.uuid = getUuid();

		String uuid = webhookCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			webhookCacheModel.uuid = null;
		}

		webhookCacheModel.webhookId = getWebhookId();

		webhookCacheModel.groupId = getGroupId();

		webhookCacheModel.companyId = getCompanyId();

		webhookCacheModel.userId = getUserId();

		webhookCacheModel.userName = getUserName();

		String userName = webhookCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			webhookCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			webhookCacheModel.createDate = createDate.getTime();
		}
		else {
			webhookCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			webhookCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			webhookCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		webhookCacheModel.webhookURL = getWebhookURL();

		String webhookURL = webhookCacheModel.webhookURL;

		if ((webhookURL != null) && (webhookURL.length() == 0)) {
			webhookCacheModel.webhookURL = null;
		}

		webhookCacheModel.apiKey = getApiKey();

		String apiKey = webhookCacheModel.apiKey;

		if ((apiKey != null) && (apiKey.length() == 0)) {
			webhookCacheModel.apiKey = null;
		}

		return webhookCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Webhook, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Webhook, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Webhook, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Webhook)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Webhook, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Webhook, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Webhook, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Webhook)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Webhook>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _webhookId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _webhookURL;
	private String _apiKey;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Webhook, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Webhook)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("webhookId", _webhookId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("webhookURL", _webhookURL);
		_columnOriginalValues.put("apiKey", _apiKey);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("webhookId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("webhookURL", 256L);

		columnBitmasks.put("apiKey", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Webhook _escapedModel;

}